name: Automated Tests

on:
  push:
    branches:
    # - main
    # - main/**
      - develop
      - develop/**
  pull_request:
    branches:
    # - main
    # - main/**
      - develop
      - develop/**

jobs:
  run-backend-tests:
    runs-on: ubuntu-latest # Switch to github-arc later
    env:
      LANG: C.UTF-8
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # We could make a code block for setting up a conda env as well
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        run: poetry config virtualenvs.create false
      
      # WORKING DIRECTORY IS ./API
      - name: Cache dependencies - api
        working-directory: ./api
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('api/poetry.lock', 'api/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies - api
        working-directory: ./api
        run: |
          poetry install --no-root |& cat
      
      - name: Run Pylint - api
        working-directory: ./api
        run: |
          poetry run pip install pylint
          poetry run pylint $(git ls-files '*.py')

      - name: Run unit tests - api
        run: |
          python -m unittest discover

      # WORKING DIRECTORY IS ./PROTOTYPES
      - name: Cache dependencies - prototypes
        working-directory: ./prototypes
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('prototypes/poetry.lock', 'prototypes/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies - prototypes
        working-directory: ./prorotypes
        run: |
          poetry install --no-root |& cat
      
      - name: Run Pylint - prototypes
        working-directory: ./prototypes
        run: |
          poetry run pip install pylint
          poetry run pylint $(git ls-files '*.py') # Only if tracked by git

      - name: Run unit tests - prototypes
        run: |
          python -m unittest discover
